Feature/feature imamura
GrowthOdyssey/TechBoard-BE pull request #1
Opened 2022-01-09 04:46 UTC by ryo-ima

## issue

記事一覧swagger作成

## 対応内容

記事一覧用swagger

## 確認してほしいこと

作り方とか、プルリクの流れはこんな感じで良いですか。（ほぼ真似しただけ）
よければ記事系の他のswaggerも作ります。

## その他

-

2022-01-10 07:30 UTC, nao11aihara requested changes
ちょろっとコメントしました！
プルリクの流れ問題ないですー、あ、プルリクのURLチャンネルに貼ってくれるとありがたいくらいです！

あと、掲示板の方先にマージしてしまったのでコンフリさせてしまいました、すみませんw

2022-01-10 07:30 UTC, nao11aihara commented on docs/swagger.yml
> +  /v1/article:
掲示板の方複数形の`threads`にしちゃったので`articles`だとありがたいです！
一般的にはどっちみたいなのは分かってないですが（単数系、複数形どっちも見たことある）

2022-01-10 07:30 UTC, nao11aihara commented on docs/swagger.yml
> +          application/json:
一覧取得、検索系のリクエストなんですけど`application/json`の形式よりクエリパラメータの方が良いですね。

一般的にリクエストの形式は以下の使い分けになっているようです〜
- パスパラメータ：特定のリソースを識別する（主に1件取得とか）
- クエリパラメータ：特定のリソースを操作して取得する（主に一覧取得、検索とか）
- リクエストボディ（json）：追加、更新する際の内容（主に作成、更新）
（参考記事：https://qiita.com/Shokorep/items/b7697a146cbb1c3e9f0b）

スレッド一覧取得ではこんな感じで書いたので参考にしていただけるとー
https://github.com/GrowthOdyssey/TechBoard-BE/blob/develop/docs/swagger.yml#L120

2022-01-10 07:30 UTC, nao11aihara commented on docs/swagger.yml
> +        articleId:
記事のレスポンスなんですけど、この形式だと複数取得の形になっていないので配列形式で返してあげる必要があります！

スレッド一覧取得のレスポンスはこんな感じにしてます！
https://github.com/GrowthOdyssey/TechBoard-BE/blob/develop/docs/swagger.yml#L120
スレッド一覧とページネーション情報のオブジェクトを作ってスレッド一覧をarrayにしている。

2022-01-14 22:37 UTC, ryo-ima commented on docs/swagger.yml
> +  /v1/article:
直しました。

2022-01-14 22:38 UTC, ryo-ima commented on docs/swagger.yml
> +          application/json:
参考にして直してみました。

2022-01-14 22:40 UTC, ryo-ima commented on docs/swagger.yml
> +        articleId:
参考にして直してみました。

2022-01-15 05:35 UTC, nao11aihara requested changes
口頭でやろうw

2022-01-15 05:35 UTC, nao11aihara commented on docs/swagger.yml
> +      summary: 記事閲覧
[imo]
取得でいいかも

2022-01-15 05:35 UTC, nao11aihara commented on docs/swagger.yml
> +                example: "2022-01-01T00:00:00+09:00"
スプレッドシートにないんですけど投稿者名欲しいですね。
`userId`と`userName`追加して良さそうです！

2022-01-15 07:36 UTC, nao11aihara approved these changes
良いかと！！！！
![LGTM](https://image.lgtmoon.dev/153031)

2022-01-15 07:37 UTC, merged